server:
  port: 9527

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
        - id: payment_routh                   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001          #匹配后提供服务的路由地址
          predicates:
            - Path=/api/payment/get/**        # 断言，路径相匹配的进行路由

        - id: payment_routh2                  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001          #匹配后提供服务的路由地址
          predicates:
            - Path=/api/payment/loadbalance/**


eureka:
  instance:
    hostname: CLOUD-GATEWAY-SERVICE
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: true
    # 是否从Eureka Server 抓取已有的注册信息，默认为true。单节点无所谓。集群必须设置为true才能Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      # 注册中心集群指向所有注册中心地址
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      # 单机注册中心指向一个地址
      defaultZone: http://eureka7001.com:7001/eureka/