server:
  port: 9002


spring:
  application:
    name: NACOS-PAYMENT-PROVIDER
  cloud:
    nacos:
      discovery:
        # 配置Nacos地址
        server-addr: localhost:8848

# RabbitMQ相关配置，暴漏bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'