server:
  port: 8401

spring:
  application:
    name: alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，加入被占用会自动从8719开始一次加一扫描，直至找到未被占用的端口
        prot: 8719

  # RabbitMQ相关配置，暴漏bus刷新配置的端点
  management:
    endpoints:
      web:
        exposure:
          include: '*'